### ISSUE TITLE
Add thiserror/anyhow

### ISSUE THREAD

**Issue by eneoli** [eneoli/flakeshot#17]

**Comment by TornaxO7** [comment]
1. [`thiserror`](https://crates.io/crates/thiserror) is already added in https://github.com/eneoli/flakeshot/pull/22
2. Rust also recommends to use [`anyhow`](https://crates.io/crates/anyhow) when [writing cli-applications](https://rust-cli.github.io/book/tutorial/errors.html#providing-context).
