### ISSUE TITLE
Basic UI with GTK and RELM4

### ISSUE THREAD

**Issue by TornaxO7** [eneoli/flakeshot#5]

**Comment by eneoli** [comment]
I don't think we can use iced here. Sadly, the Wayland Protocol limits the possibilities of a window including deciding where it want's to be placed. Also iced does not support multiple windows at the time writing this.

We need to search for an alternative. A possible scenario would be to directly write wayland client code using [`wlr_layer_shell`](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) but I would like to avoid this for two reasons:

1. Compatibility with X11
2. Wayland requires some sort of RGB Buffer for the contents of the layer. So we need a GUI lib that outputs to a buffer.

**Comment by eneoli** [comment]
Just as a side note:

We switch to GTK4 + GTK4 Layer Shell for Wayland support. We'll use relm4 to make the UI a bit easier to develop (hopefully)
