### ISSUE TITLE
Tray: Add image

### ISSUE THREAD

**Issue by TornaxO7** [eneoli/flakeshot#84]

**Comment by TornaxO7** [comment]
@eneoli I need the PNG variant of the icon because the tray crate doesn't accept svg files and there doesn't seem to be a crate which can convert a svg file into a png file.

**Comment by eneoli** [comment]
Which resolution do you need? Can’t you convert the svg to a png using gimp or something else?

**Comment by TornaxO7** [comment]
> Can’t you convert the svg to a png using gimp or something else?

oh lol, fair point
